### PR TITLE
BE user by playlist, FE save playlist and display saved playlisst in profile

### PR DESCRIPTION
**Pull request by allansomera**
Backend:
-created userbyplaylist table for connecting a user and it's playlists
-added saveplaylist endpoint
-added getuserplaylists endpoint

Frontend:
-implemented save functionality on button click after generating a playlist
-displayed saved playlists on profile section

### CODE REVIEW

**Comment by allansomera** [comment]
[FE- User Profile History Page/Tab](https://trello.com/c/iXgxao3i/14-fe-user-profile-history-page-tab)

**Comment by allansomera** [comment]
[BE - implement users by playlist table](https://trello.com/c/sQ6J8aNu/24-be-implement-users-by-playlist-table)

**Review by jackytam2020 — COMMENTED** [review]
The code looks good. Also wouldn't it be better just to call the user.recommended global variable instead to get the recommended playlist instead of using another localStorage function in Playlistgen and SavedPlaylists comp? We're already setting the initial state of recommended in the context to a localStorage getItem value of recommended playlist. Same for user profile

**Comment by allansomera** [comment]
good point, i'll change it to use the data we stored in our user context instead

**Comment by allansomera** [comment]
minimal functionality on spotify embed, need to fix not showing up on refresh
- using save button just for testing, will get rid of it after fixing minor bugs
- successfully creating playlist on user's profile

**Review by emwong101 — APPROVED** [review]
Looks good, can be merged after review @jackytam2020

**Comment by allansomera** [comment]
[FE - grab saved playlists from backend instead of user context instead](https://trello.com/c/HQjIjYfV/26-fe-grab-saved-playlists-from-backend-instead-of-user-context-instead)

**Pull request merged**
